# config.generated.yaml is written by `terraform apply` and committed to git.
# It contains values that depend on the GCP project state (the WIF provider
# path includes the project NUMBER, which TF only knows after talking to GCP).
#
# The CI workflow reads BOTH config.yaml (hand-edited) and config.generated.yaml
# (TF-written) to compose its deploy command.
#
# After first apply: `git add infra/config.generated.yaml && git commit && git push`.
resource "local_file" "config_generated" {
  filename = "${path.module}/config.generated.yaml"
  content = <<-EOT
    # AUTO-GENERATED by `terraform apply` — do NOT edit by hand.
    # To change these values, edit infra/config.yaml and re-apply.
    ${yamlencode({
  gcp_wif_provider      = google_iam_workload_identity_pool_provider.github_actions.name
  gcp_deploy_sa         = google_service_account.deploy.email
  gcp_runtime_sa        = google_service_account.runtime.email
  gcp_artifact_registry = "${local.config.gcp_region}-docker.pkg.dev/${local.config.gcp_project_id}/${google_artifact_registry_repository.sam.repository_id}"
  gcs_data_bucket       = google_storage_bucket.sam_data.name
})}
  EOT
  file_permission = "0644"
}
